'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const ROOT = path.join(__dirname, '..')
const read = name => fs.readFileSync(path.join(ROOT, name), 'utf8')
const pkg = JSON.parse(read('package.json'))
const start = String(pkg.scripts && pkg.scripts.start || '')
const preload = read('download-reliability-preload.js')
const clientPreload = read('download-client-reliability-preload.js')
const resolver = read('download-reference-resolver.js')
const uploads = read('public/uploads.js')
const clientUi = read('public/download-reliability.js')
const css = read('public/download-reliability.css')
const updateBoundary = read('bulk-upload-preload.js')

const bulkAt = start.indexOf('-r ./bulk-upload-preload.js')
const clientAt = start.indexOf('-r ./download-client-reliability-preload.js')
const dedupeAt = start.indexOf('-r ./download-dedupe-preload.js')
const reliabilityAt = start.indexOf('-r ./download-reliability-preload.js')
const serverAt = start.lastIndexOf('server.js')
assert.ok(bulkAt >= 0, 'bulk preload must remain installed so download reliability can share the live TDLib client')
assert.ok(clientAt > bulkAt, 'download client reliability must wrap the client returned by the bulk preload')
assert.ok(dedupeAt > clientAt, 'download dedupe must load after the TDLib client reliability boundary')
assert.ok(reliabilityAt > dedupeAt, 'download reference reliability must wrap start-download after dedupe is installed')
assert.ok(serverAt > reliabilityAt, 'download reliability must run before server.js')

assert.match(preload, /request\.type !== REQUEST_TYPE/)
assert.match(preload, /resolveDownloadItems/)
assert.match(preload, /fileGramTdlibSafeRename/)
assert.match(preload, /inside\(from, TD_FILES_DIR\)/)
assert.match(preload, /registered:\s*report\.registered/)
assert.match(preload, /sendEvent\(socket, 'download-reference-repair'/)
assert.match(resolver, /chat_id: chatId/)
assert.match(resolver, /getChatHistory/)
assert.match(resolver, /getMessage/)
assert.match(resolver, /getRemoteFile/)
assert.match(resolver, /remote_file_id:\s*remoteId/)
assert.match(resolver, /file_type:\s*null/)
assert.match(resolver, /remoteRegistrations = new Map/)
assert.match(resolver, /DIRECT_LOOKUP_LIMIT/)
assert.match(resolver, /originalById = new Map/)

assert.match(clientPreload, /invokeDownloadWithRetry/)
assert.match(clientPreload, /local\.can_be_downloaded/)
assert.match(clientPreload, /query\._ === 'downloadFile'/)
assert.match(clientPreload, /query\._ === 'getFile'/)

assert.match(uploads, /download-reliability\.css\?v=1/)
assert.match(uploads, /download-reliability\.js\?v=1/)
assert.match(clientUi, /installCompletedMarkerBoundary/)
assert.match(clientUi, /completedBypass/)
assert.match(css, /content-visibility:\s*visible\s*!important/)
assert.match(css, /contain:\s*none\s*!important/)
assert.match(css, /min-height:\s*58px\s*!important/)

assert.match(updateBoundary, /UPDATE_FILE_PROGRESS_INTERVAL_MS = 200/)
assert.match(updateBoundary, /client\.off = function fileGramBoundaryOff/)
assert.match(updateBoundary, /client\.removeListener = function fileGramBoundaryRemoveListener/)
assert.match(updateBoundary, /updateWrappers\.delete\(listener\)/)

console.log('download reliability wiring checks passed')
