'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const ROOT = path.join(__dirname, '..')
const read = name => fs.readFileSync(path.join(ROOT, name), 'utf8')
const pkg = JSON.parse(read('package.json'))
const uploads = read('public/uploads.js')
const preload = read('bulk-upload-preload.js')
const reliability = read('public/upload-reliability.js')
const uiStability = read('public/filegram-ui-stability.js')

const start = String(pkg.scripts && pkg.scripts.start || '')
const reliabilityAt = start.indexOf('-r ./bulk-upload-reliability-preload.js')
const bulkAt = start.indexOf('-r ./bulk-upload-preload.js')
assert.ok(reliabilityAt >= 0, 'server reliability preload must be part of npm start')
assert.ok(bulkAt > reliabilityAt, 'server reliability boundary must load before bulk-upload-preload')

assert.match(uploads, /filegram-ui-stability\.js\?v=1/)
assert.match(uploads, /filegram-media-preview\.js\?v=1/)
assert.match(uploads, /upload-reliability\.js\?v=3/)
assert.match(uploads, /uploads-hardening\.js\?v=3/)
assert.match(uploads, /hardening\.addEventListener\('load',\s*loadPostHardening/)
assert.match(uploads, /existingHardening\.addEventListener\('load',\s*loadPostHardening/)

assert.match(preload, /\/api\/filegram\/bulk-upload-status\/:uploadId/)
assert.match(preload, /Cache-Control.*no-store/)
assert.match(preload, /active\.has\(uploadId\)/)
assert.match(preload, /fileGramProgressInvoke/)
assert.match(preload, /uploadIdFromLocalPath/)
assert.match(preload, /update\._ !== 'updateFile'/)
assert.match(preload, /rememberUploadFile\(uploadId, fileFromMessage\(result\)\)/)
assert.match(preload, /getFile.*file_id/)
assert.match(preload, /remote\.uploaded_size/)
assert.match(preload, /telegramProgressAvailable/)
assert.match(reliability, /Uploading \$\{.*percent/)
assert.match(reliability, /telegramUploadedBytes/)
assert.match(reliability, /pollTelegramProgress/)
assert.match(reliability, /job\.progress = job\._telegramProgressAvailable/)

assert.match(uiStability, /window\.toast = stableToast/)
assert.match(uiStability, /#fg-upload-speed\[hidden\]/)
assert.match(uiStability, /fg-upload-live-status/)
assert.match(uiStability, /data-fg-live-status/)
assert.match(uiStability, /MutationObserver/)
assert.doesNotMatch(uiStability, /void\s+.*offsetWidth|className\s*=/, 'stable toast must not retrigger visibility through forced reflow/class reset')

console.log('media/upload wiring checks passed')
