'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs')

const server = fs.readFileSync('server.js', 'utf8')
const app = fs.readFileSync('public/app.js', 'utf8')
const html = fs.readFileSync('public/index.html', 'utf8')
const management = fs.readFileSync('public/management.js', 'utf8')

assert.match(server, /_:\s*'forwardMessages'/, 'native TDLib forwardMessages must be present')
assert.match(server, /send_copy:\s*false/, 'forwarding must preserve native forwarded-message semantics')
assert.match(server, /case 'forward-messages'/, 'websocket forwarding command must be present')
assert.match(server, /case 'search-destinations'/, 'destination search command must be present')
assert.match(server, /updateNewChat/, 'new chats must be published to the UI')
assert.match(server, /chat-upsert/, 'chat upsert realtime event must be present')
assert.match(server, /server\.listen\(PORT, '127\.0\.0\.1'/, 'runtime must bind only to loopback')

assert.match(app, /selectedMessages:\s*new Map\(\)/, 'text-message selection state must exist')
assert.match(app, /forwardSelectedMessages/, 'forward UI action must exist')
assert.match(app, /case 'chat-upsert'/, 'UI must reconcile realtime chat updates')
assert.match(app, /searchForwardDestinations/, 'UI must resolve destinations through the backend')
assert.match(html, /id="forward-selected"/, 'selection bar must expose Forward')

console.log('rescue smoke checks passed')

assert.match(server, /createNewSupergroupChat/, 'channel and group creation must use TDLib')
assert.match(server, /case 'get-chat-management'/, 'permission-aware chat management command must exist')
assert.match(server, /deleteChatHistory/, 'clear-history support must exist')
assert.match(server, /leaveChat/, 'leave-chat support must exist')
assert.match(server, /deleteChat/, 'permission-aware delete support must exist')
assert.match(management, /Create link/, 'chat info drawer must expose invite management')
assert.match(management, /Load members/, 'chat info drawer must expose member management')
assert.match(html, /management\.js/, 'management runtime must be loaded')

const rescueRuntime = fs.readFileSync('public/rescue-runtime.js', 'utf8')
const managementCss = fs.readFileSync('public/management.css', 'utf8')
const modernCss = fs.readFileSync('public/modern.css', 'utf8')
assert.match(server, /updateNewMessage/, 'new Telegram messages must be pushed in realtime')
assert.match(server, /updateDeleteMessages/, 'message deletions must be pushed in realtime')
assert.match(server, /message-upsert/, 'server must publish realtime message upserts')
assert.match(server, /message-delete/, 'server must publish realtime message deletions')
assert.match(server, /\.png/, 'chat photo endpoint must support PNG')
assert.match(rescueRuntime, /rescueRealtimeMessageUpsert/, 'client must merge realtime messages into cache')
assert.match(rescueRuntime, /rescueSortChatsRecentFirst/, 'chat list must enforce recent-first order')
assert.match(management, /image\/png/, 'chat photo UI must accept PNG')
assert.match(managementCss, /mg-photo-drop/, 'chat photo UI must use the polished upload surface')

assert.match(server, /getMessageProperties/, 'message actions must be permission-aware')
assert.match(server, /sendMessage/, 'chat composer must send through TDLib')
assert.match(server, /editMessageText/, 'text editing must use TDLib')
assert.match(server, /deleteMessages/, 'message deletion must use TDLib')
assert.match(server, /canClearHistoryForSelf/, 'clear history must distinguish self/all permissions')
assert.match(server, /managedSupergroupFullInfoCache/, 'invite-link/full-info updates must use authoritative realtime cache')
assert.match(management, /Desktop notifications/, 'desktop notification controls must exist')
assert.match(management, /Clear history for everyone/, 'history UI must expose valid revoke mode')

assert.match(server, /replacePrimaryChatInviteLink/, 'invite links must use primary Telegram invite-link management')
assert.match(server, /inputMessageDocument/, 'chat attachments must send through TDLib')
assert.match(server, /api\/chat-attachment/, 'chat attachment streaming endpoint must exist')
assert.match(rescueRuntime, /tele-compose-attach/, 'chat composer must expose file attachment')
assert.match(rescueRuntime, /serviceWorker/, 'desktop notifications must use service-worker delivery when available')
assert.match(management, /Test/, 'notification settings must expose a test action')
assert.doesNotMatch(management, /check-managed-username/, 'channel/group username management must be removed from the UI')

assert.match(server, /preliminaryUploadFile/, 'attachments must be registered with TDLib before send')
assert.match(server, /inputFileId/, 'attachments must send using a validated TDLib file id')
assert.match(rescueRuntime, /rescueMarkActiveChat/, 'chat switching must update active state without rebuilding the sidebar')
assert.match(html, /modern\.css/, 'modern desktop skin must be loaded')
assert.match(modernCss, /Tele modern desktop skin/, 'modern UI skin must exist')
